[tool.poetry]
name = "chainlit-chatbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
common-lib = { path = "../common-lib", develop=true }
python = "^3.11,<3.13"
chainlit = "^1.1.304"
