[tool.poetry]
name = "common-lib"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.28.0"
jupyterlab = "^4.2.0"
nbdev = "^2.3.20"
setuptools = "^69.5.1"
multidict = "^6.1.0"
