[tool.poetry]
name = "common-lib"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.28.1"
jupyterlab = "^4.0.11"
nbdev = "^2.3.13"
